version: "2"
services:
  my_page_counter_and_item_storage_app:
    image: annakrih/week1:day2
    ports:
     - "3000:3000"
    links:
     - my_redis_container
     - my_postgres_cointainer
  my_redis_container:
    image: redis
  my_postgres_cointainer:
    image: postgres
    environment:
      POSTGRES_DB: 'hgopDB'
      POSTGRES_USER: 'postgresAdmin'
      POSTGRES_PASSWORD: 'AnnaKristin'
