node {
    checkout scm
    stage('Build') {
        echo 'Building..'
        sh 'make' 
        archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true 
    }
    stage('Test') {
        echo 'actually, there are no tests...'
    }
    stage('Deploy') {
        echo 'Deploying....'
        sh 'make publish'
    }
}
