version: "2"
services:
  my_page_counter_app_and_item_storage_app:
    image: annakrih/week1:day2
    ports:
     - "3000:3000"
    links:
     - my_redis_container
  my_redis_container:
    image: redis
